interface Tag {
	tagName: string;
	tagCategory: string;
}
const duplicateTags: Tag[] = [
	{ tagName: "JavaScript", tagCategory: "technical-skills" },
	{ tagName: "Python", tagCategory: "technical-skills" },
	{ tagName: "Java", tagCategory: "technical-skills" },
	{ tagName: "React", tagCategory: "technical-skills" },
	{ tagName: "Node.js", tagCategory: "technical-skills" },
	{ tagName: "Git", tagCategory: "technical-skills" },
	{ tagName: "Github", tagCategory: "technical-skills" },
	{ tagName: "Docker", tagCategory: "technical-skills" },
	{ tagName: "AWS", tagCategory: "technical-skills" },
	{ tagName: "SQL", tagCategory: "technical-skills" },
	{ tagName: "HTML/CSS", tagCategory: "technical-skills" },
	{ tagName: "Data Structures", tagCategory: "problem-solving" },
	{ tagName: "Algorithms", tagCategory: "problem-solving" },
	{ tagName: "Dynamic Programming", tagCategory: "problem-solving" },
	{ tagName: "Sorting", tagCategory: "problem-solving" },
	{ tagName: "Recursion", tagCategory: "problem-solving" },
	{ tagName: "Graphs", tagCategory: "problem-solving" },
	{ tagName: "Big O Notation", tagCategory: "problem-solving" },
	{ tagName: "Hash Tables", tagCategory: "problem-solving" },
	{ tagName: "Binary Search", tagCategory: "problem-solving" },
	{ tagName: "Linked Lists", tagCategory: "problem-solving" },
	{ tagName: "Scalability", tagCategory: "system-design" },
	{ tagName: "Reliability", tagCategory: "system-design" },
	{ tagName: "Microservices", tagCategory: "system-design" },
	{ tagName: "Load Balancing", tagCategory: "system-design" },
	{ tagName: "Databases", tagCategory: "system-design" },
	{ tagName: "Caching", tagCategory: "system-design" },
	{ tagName: "Messaging Queues", tagCategory: "system-design" },
	{ tagName: "Design Patterns", tagCategory: "system-design" },
	{ tagName: "Fault Tolerance", tagCategory: "system-design" },
	{ tagName: "High Availability", tagCategory: "system-design" },
	{ tagName: "Teamwork", tagCategory: "behavioral" },
	{ tagName: "Communication", tagCategory: "behavioral" },
	{ tagName: "Leadership", tagCategory: "behavioral" },
	{ tagName: "Conflict Resolution", tagCategory: "behavioral" },
	{ tagName: "Problem-Solving", tagCategory: "behavioral" },
	{ tagName: "Adaptability", tagCategory: "behavioral" },
	{ tagName: "Time Management", tagCategory: "behavioral" },
	{ tagName: "Decision Making", tagCategory: "behavioral" },
	{ tagName: "Creativity", tagCategory: "behavioral" },
	{ tagName: "Stress Management", tagCategory: "behavioral" },
	{ tagName: "Agile Methodology", tagCategory: "practical-knowledge" },
	{ tagName: "Security Best Practices", tagCategory: "practical-knowledge" },
	{ tagName: "User Experience (UX)", tagCategory: "practical-knowledge" },
	{ tagName: "User Interface (UI)", tagCategory: "practical-knowledge" },
	{ tagName: "Data Visualization", tagCategory: "practical-knowledge" },
	{ tagName: "Compliance Standards", tagCategory: "practical-knowledge" },
	{ tagName: "Industry Regulations", tagCategory: "practical-knowledge" },
	{ tagName: "Version Control", tagCategory: "practical-knowledge" },
	{ tagName: "Deployment Strategies", tagCategory: "practical-knowledge" },
	{ tagName: "Testing Techniques", tagCategory: "practical-knowledge" },
	{ tagName: "JavaScript", tagCategory: "technical-skills" },
	{ tagName: "Python", tagCategory: "technical-skills" },
	{ tagName: "Java", tagCategory: "technical-skills" },
	{ tagName: "C++", tagCategory: "technical-skills" },
	{ tagName: "SQL", tagCategory: "technical-skills" },
	{ tagName: "C#", tagCategory: "technical-skills" },
	{ tagName: "React", tagCategory: "technical-skills" },
	{ tagName: "Node.js", tagCategory: "technical-skills" },
	{ tagName: "AWS", tagCategory: "technical-skills" },
	{ tagName: "HTML/CSS", tagCategory: "technical-skills" },
	{ tagName: "Docker", tagCategory: "technical-skills" },
	{ tagName: "Git", tagCategory: "technical-skills" },
	{ tagName: "TypeScript", tagCategory: "technical-skills" },
	{ tagName: "Kubernetes", tagCategory: "technical-skills" },
	{ tagName: "Ruby", tagCategory: "technical-skills" },
	{ tagName: "PHP", tagCategory: "technical-skills" },
	{ tagName: "Go", tagCategory: "technical-skills" },
	{ tagName: "Swift", tagCategory: "technical-skills" },
	{ tagName: "Angular", tagCategory: "technical-skills" },
	{ tagName: "Django", tagCategory: "technical-skills" },
	{ tagName: "Flask", tagCategory: "technical-skills" },
	{ tagName: "Spring Boot", tagCategory: "technical-skills" },
	{ tagName: "Vue.js", tagCategory: "technical-skills" },
	{ tagName: "Rust", tagCategory: "technical-skills" },
	{ tagName: "Scala", tagCategory: "technical-skills" },
	{ tagName: "Kotlin", tagCategory: "technical-skills" },
	{ tagName: "MATLAB", tagCategory: "technical-skills" },
	{ tagName: "Perl", tagCategory: "technical-skills" },
	{ tagName: "R", tagCategory: "technical-skills" },
	{ tagName: "Selenium", tagCategory: "technical-skills" },
	{ tagName: "GraphQL", tagCategory: "technical-skills" },
	{ tagName: "Terraform", tagCategory: "technical-skills" },
	{ tagName: "Pandas", tagCategory: "technical-skills" },
	{ tagName: "NumPy", tagCategory: "technical-skills" },
	{ tagName: "TensorFlow", tagCategory: "technical-skills" },
	{ tagName: "PyTorch", tagCategory: "technical-skills" },
	{ tagName: "React Native", tagCategory: "technical-skills" },
	{ tagName: "Firebase", tagCategory: "technical-skills" },
	{ tagName: "Redux", tagCategory: "technical-skills" },
	{ tagName: "MongoDB", tagCategory: "technical-skills" },
	{ tagName: "PostgreSQL", tagCategory: "technical-skills" },
	{ tagName: "MySQL", tagCategory: "technical-skills" },
	{ tagName: "Redis", tagCategory: "technical-skills" },
	{ tagName: "Elasticsearch", tagCategory: "technical-skills" },
	{ tagName: "jQuery", tagCategory: "technical-skills" },
	{ tagName: "SASS/SCSS", tagCategory: "technical-skills" },
	{ tagName: "LESS", tagCategory: "technical-skills" },
	{ tagName: "Webpack", tagCategory: "technical-skills" },
	{ tagName: "Gulp", tagCategory: "technical-skills" },
	{ tagName: "Gradle", tagCategory: "technical-skills" },
	{ tagName: "Maven", tagCategory: "technical-skills" },
	{ tagName: "Apache Kafka", tagCategory: "technical-skills" },
	{ tagName: "RabbitMQ", tagCategory: "technical-skills" },
	{ tagName: "Nginx", tagCategory: "technical-skills" },
	{ tagName: "GraphQL", tagCategory: "technical-skills" },
	{ tagName: "Express.js", tagCategory: "technical-skills" },
	{ tagName: "ASP.NET", tagCategory: "technical-skills" },
	{ tagName: "Vue.js", tagCategory: "technical-skills" },
	{ tagName: "Next.js", tagCategory: "technical-skills" },
	{ tagName: "Nuxt.js", tagCategory: "technical-skills" },
	{ tagName: "Gatsby", tagCategory: "technical-skills" },
	{ tagName: "Hadoop", tagCategory: "technical-skills" },
	{ tagName: "Spark", tagCategory: "technical-skills" },
	{ tagName: "Hive", tagCategory: "technical-skills" },
	{ tagName: "Flink", tagCategory: "technical-skills" },
	{ tagName: "Keras", tagCategory: "technical-skills" },
	{ tagName: "Caffe", tagCategory: "technical-skills" },
	{ tagName: "OpenCV", tagCategory: "technical-skills" },
	{ tagName: "NLTK", tagCategory: "technical-skills" },
	{ tagName: "spaCy", tagCategory: "technical-skills" },
	{ tagName: "Beautiful Soup", tagCategory: "technical-skills" },
	{ tagName: "Scrapy", tagCategory: "technical-skills" },
	{ tagName: "Requests", tagCategory: "technical-skills" },
	{ tagName: "FastAPI", tagCategory: "technical-skills" },
	{ tagName: "CherryPy", tagCategory: "technical-skills" },
	{ tagName: "Pyramid", tagCategory: "technical-skills" },
	{ tagName: "Bottle", tagCategory: "technical-skills" },
	{ tagName: "Falcon", tagCategory: "technical-skills" },
	{ tagName: "Tornado", tagCategory: "technical-skills" },
	{ tagName: "Peewee", tagCategory: "technical-skills" },
	{ tagName: "SQLAlchemy", tagCategory: "technical-skills" },
	{ tagName: "Alembic", tagCategory: "technical-skills" },
	{ tagName: "Marshmallow", tagCategory: "technical-skills" },
	{ tagName: "Pytest", tagCategory: "technical-skills" },
	{ tagName: "Unittest", tagCategory: "technical-skills" },
	{ tagName: "Jest", tagCategory: "technical-skills" },
	{ tagName: "Mocha", tagCategory: "technical-skills" },
	{ tagName: "Chai", tagCategory: "technical-skills" },
	{ tagName: "Jasmine", tagCategory: "technical-skills" },
	{ tagName: "Karma", tagCategory: "technical-skills" },
	{ tagName: "Protractor", tagCategory: "technical-skills" },
	{ tagName: "Cypress", tagCategory: "technical-skills" },
	{ tagName: "Selenium", tagCategory: "technical-skills" },
	{ tagName: "Puppeteer", tagCategory: "technical-skills" },
	{ tagName: "Playwright", tagCategory: "technical-skills" },
	{ tagName: "Jupyter", tagCategory: "technical-skills" },
	{ tagName: "VSCode", tagCategory: "technical-skills" },
	{ tagName: "Eclipse", tagCategory: "technical-skills" },
	{ tagName: "IntelliJ IDEA", tagCategory: "technical-skills" },
	{ tagName: "PyCharm", tagCategory: "technical-skills" },
	{ tagName: "NetBeans", tagCategory: "technical-skills" },
	{ tagName: "WebStorm", tagCategory: "technical-skills" },
	{ tagName: "Xcode", tagCategory: "technical-skills" },
	{ tagName: "Android Studio", tagCategory: "technical-skills" },
	{ tagName: "Emacs", tagCategory: "technical-skills" },
	{ tagName: "Vim", tagCategory: "technical-skills" },
	{ tagName: "C", tagCategory: "technical-skills" },
	{ tagName: "C++", tagCategory: "technical-skills" },
	{ tagName: "C#", tagCategory: "technical-skills" },
	{ tagName: "Go", tagCategory: "technical-skills" },
	{ tagName: "Rust", tagCategory: "technical-skills" },
	{ tagName: "Kotlin", tagCategory: "technical-skills" },
	{ tagName: "Swift", tagCategory: "technical-skills" },
	{ tagName: "TypeScript", tagCategory: "technical-skills" },
	{ tagName: "Ruby", tagCategory: "technical-skills" },
	{ tagName: "PHP", tagCategory: "technical-skills" },
	{ tagName: "Perl", tagCategory: "technical-skills" },
	{ tagName: "R", tagCategory: "technical-skills" },
	{ tagName: "MATLAB", tagCategory: "technical-skills" },
	{ tagName: "Scala", tagCategory: "technical-skills" },
	{ tagName: "Groovy", tagCategory: "technical-skills" },
	{ tagName: "Objective-C", tagCategory: "technical-skills" },
	{ tagName: "Dart", tagCategory: "technical-skills" },
	{ tagName: "Lua", tagCategory: "technical-skills" },
	{ tagName: "Haskell", tagCategory: "technical-skills" },
	{ tagName: "Elixir", tagCategory: "technical-skills" },
	{ tagName: "Clojure", tagCategory: "technical-skills" },
	{ tagName: "F#", tagCategory: "technical-skills" },
	{ tagName: "Erlang", tagCategory: "technical-skills" },
	{ tagName: "VHDL", tagCategory: "technical-skills" },
	{ tagName: "Verilog", tagCategory: "technical-skills" },
	{ tagName: "Ada", tagCategory: "technical-skills" },
	{ tagName: "Fortran", tagCategory: "technical-skills" },
	{ tagName: "COBOL", tagCategory: "technical-skills" },
	{ tagName: "Lisp", tagCategory: "technical-skills" },
	{ tagName: "Prolog", tagCategory: "technical-skills" },
	{ tagName: "Smalltalk", tagCategory: "technical-skills" },
	{ tagName: "Scheme", tagCategory: "technical-skills" },
	{ tagName: "AWK", tagCategory: "technical-skills" },
	{ tagName: "PostScript", tagCategory: "technical-skills" },
	{ tagName: "ActionScript", tagCategory: "technical-skills" },
	{ tagName: "Scratch", tagCategory: "technical-skills" },
	{ tagName: "SAS", tagCategory: "technical-skills" },
	{ tagName: "Julia", tagCategory: "technical-skills" },
	{ tagName: "Racket", tagCategory: "technical-skills" },
	{ tagName: "APL", tagCategory: "technical-skills" },
	{ tagName: "OCaml", tagCategory: "technical-skills" },
	{ tagName: "ABAP", tagCategory: "technical-skills" },
	{ tagName: "D", tagCategory: "technical-skills" },
	{ tagName: "Nim", tagCategory: "technical-skills" },
	{ tagName: "Crystal", tagCategory: "technical-skills" },
	{ tagName: "Solidity", tagCategory: "technical-skills" },
	{ tagName: "Angular", tagCategory: "technical-skills" },
	{ tagName: "Vue", tagCategory: "technical-skills" },
	{ tagName: "Svelte", tagCategory: "technical-skills" },
	{ tagName: "Ember.js", tagCategory: "technical-skills" },
	{ tagName: "Backbone.js", tagCategory: "technical-skills" },
	{ tagName: "Express", tagCategory: "technical-skills" },
	{ tagName: "Nextjs", tagCategory: "technical-skills" },
	{ tagName: "Nodejs", tagCategory: "technical-skills" },
	{ tagName: "Gatsby", tagCategory: "technical-skills" },
	{ tagName: "Spring Boot", tagCategory: "technical-skills" },
	{ tagName: "Flask", tagCategory: "technical-skills" },
	{ tagName: "Django", tagCategory: "technical-skills" },
	{ tagName: "Ruby on Rails", tagCategory: "technical-skills" },
	{ tagName: "Laravel", tagCategory: "technical-skills" },
	{ tagName: "Symfony", tagCategory: "technical-skills" },
	{ tagName: "Superbase", tagCategory: "technical-skills" },
	{ tagName: "ASP.NET Core", tagCategory: "technical-skills" },
	{ tagName: "Meteor", tagCategory: "technical-skills" },
	{ tagName: "LoopBack", tagCategory: "technical-skills" },
	{ tagName: "Feathers.js", tagCategory: "technical-skills" },
	{ tagName: "Hapi.js", tagCategory: "technical-skills" },
	{ tagName: "Socket.IO", tagCategory: "technical-skills" },
	{ tagName: "Electron", tagCategory: "technical-skills" },
	{ tagName: "Ionic", tagCategory: "technical-skills" },
	{ tagName: "Cordova", tagCategory: "technical-skills" },
	{ tagName: "NativeScript", tagCategory: "technical-skills" },
	{ tagName: "React-Native", tagCategory: "technical-skills" },
	{ tagName: "Flutter", tagCategory: "technical-skills" },
	{ tagName: "Xamarin", tagCategory: "technical-skills" },
	{ tagName: "Pandas", tagCategory: "technical-skills" },
	{ tagName: "NumPy", tagCategory: "technical-skills" },
	{ tagName: "SciPy", tagCategory: "technical-skills" },
	{ tagName: "Matplotlib", tagCategory: "technical-skills" },
	{ tagName: "Seaborn", tagCategory: "technical-skills" },
	{ tagName: "TensorFlow", tagCategory: "technical-skills" },
	{ tagName: "Keras", tagCategory: "technical-skills" },
	{ tagName: "PyTorch", tagCategory: "technical-skills" },
	{ tagName: "Scikit-Learn", tagCategory: "technical-skills" },
	{ tagName: "OpenCV", tagCategory: "technical-skills" },
	{ tagName: "NLTK", tagCategory: "technical-skills" },
	{ tagName: "spaCy", tagCategory: "technical-skills" },
	{ tagName: "Beautiful Soup", tagCategory: "technical-skills" },
	{ tagName: "Scrapy", tagCategory: "technical-skills" },
	{ tagName: "Requests", tagCategory: "technical-skills" },
	{ tagName: "FastAPI", tagCategory: "technical-skills" },
	{ tagName: "CherryPy", tagCategory: "technical-skills" },
	{ tagName: "Pyramid", tagCategory: "technical-skills" },
	{ tagName: "Bottle", tagCategory: "technical-skills" },
	{ tagName: "Falcon", tagCategory: "technical-skills" },
	{ tagName: "Tornado", tagCategory: "technical-skills" },
	{ tagName: "Peewee", tagCategory: "technical-skills" },
	{ tagName: "SQLAlchemy", tagCategory: "technical-skills" },
	{ tagName: "Alembic", tagCategory: "technical-skills" },
	{ tagName: "Marshmallow", tagCategory: "technical-skills" },
	{ tagName: "Pytest", tagCategory: "technical-skills" },
	{ tagName: "Unittest", tagCategory: "technical-skills" },
	{ tagName: "Jest", tagCategory: "technical-skills" },
	{ tagName: "Mocha", tagCategory: "technical-skills" },
	{ tagName: "Chai", tagCategory: "technical-skills" },
	{ tagName: "Jasmine", tagCategory: "technical-skills" },
	{ tagName: "Karma", tagCategory: "technical-skills" },
	{ tagName: "Protractor", tagCategory: "technical-skills" },
	{ tagName: "Cypress", tagCategory: "technical-skills" },
	{ tagName: "Selenium", tagCategory: "technical-skills" },
	{ tagName: "Puppeteer", tagCategory: "technical-skills" },
	{ tagName: "Playwright", tagCategory: "technical-skills" },
	{ tagName: "Jupyter", tagCategory: "technical-skills" },
	{ tagName: "VSCode", tagCategory: "technical-skills" },
	{ tagName: "Eclipse", tagCategory: "technical-skills" },
	{ tagName: "IntelliJ IDEA", tagCategory: "technical-skills" },
	{ tagName: "PyCharm", tagCategory: "technical-skills" },
	{ tagName: "NetBeans", tagCategory: "technical-skills" },
	{ tagName: "WebStorm", tagCategory: "technical-skills" },
	{ tagName: "Sublime Text", tagCategory: "technical-skills" },
	{ tagName: "Atom", tagCategory: "technical-skills" },
	{ tagName: "Vim", tagCategory: "technical-skills" },
	{ tagName: "Emacs", tagCategory: "technical-skills" },
	{ tagName: "CMake", tagCategory: "technical-skills" },
	{ tagName: "Make", tagCategory: "technical-skills" },
	{ tagName: "Gulp", tagCategory: "technical-skills" },
	{ tagName: "Grunt", tagCategory: "technical-skills" },
	{ tagName: "Webpack", tagCategory: "technical-skills" },
	{ tagName: "Parcel", tagCategory: "technical-skills" },
	{ tagName: "Rollup", tagCategory: "technical-skills" },
	{ tagName: "Browserify", tagCategory: "technical-skills" },
	{ tagName: "ESLint", tagCategory: "technical-skills" },
	{ tagName: "Prettier", tagCategory: "technical-skills" },
	{ tagName: "TSLint", tagCategory: "technical-skills" },
	{ tagName: "Stylelint", tagCategory: "technical-skills" },
	{ tagName: "Storybook", tagCategory: "technical-skills" },
	{ tagName: "Lodash", tagCategory: "technical-skills" },
	{ tagName: "Moment.js", tagCategory: "technical-skills" },
	{ tagName: "Ramda", tagCategory: "technical-skills" },
	{ tagName: "RxJS", tagCategory: "technical-skills" },
	{ tagName: "Immutable.js", tagCategory: "technical-skills" },
	{ tagName: "D3.js", tagCategory: "technical-skills" },
	{ tagName: "Chart.js", tagCategory: "technical-skills" },
	{ tagName: "Three.js", tagCategory: "technical-skills" },
	{ tagName: "p5.js", tagCategory: "technical-skills" },
	{ tagName: "Babylon.js", tagCategory: "technical-skills" },
	{ tagName: "TensorFlow.js", tagCategory: "technical-skills" },
	{ tagName: "Tree Traversal", tagCategory: "problem-solving" },
	{ tagName: "Backtracking", tagCategory: "problem-solving" },
	{ tagName: "Greedy Algorithms", tagCategory: "problem-solving" },
	{ tagName: "Divide and Conquer", tagCategory: "problem-solving" },
	{ tagName: "Breadth-First Search", tagCategory: "problem-solving" },
	{ tagName: "Depth-First Search", tagCategory: "problem-solving" },
	{ tagName: "Trie", tagCategory: "problem-solving" },
	{ tagName: "Heaps", tagCategory: "problem-solving" },
	{ tagName: "Bit Manipulation", tagCategory: "problem-solving" },
	{ tagName: "Union-Find", tagCategory: "problem-solving" },
	{ tagName: "Scalability", tagCategory: "system-design" },
	{ tagName: "Reliability", tagCategory: "system-design" },
	{ tagName: "Microservices", tagCategory: "system-design" },
	{ tagName: "Load Balancing", tagCategory: "system-design" },
	{ tagName: "Databases", tagCategory: "system-design" },
	{ tagName: "Caching", tagCategory: "system-design" },
	{ tagName: "Messaging Queues", tagCategory: "system-design" },
	{ tagName: "Design Patterns", tagCategory: "system-design" },
	{ tagName: "Fault Tolerance", tagCategory: "system-design" },
	{ tagName: "High Availability", tagCategory: "system-design" },
	{ tagName: "Service-Oriented Architecture", tagCategory: "system-design" },
	{ tagName: "API Design", tagCategory: "system-design" },
	{ tagName: "Data Consistency", tagCategory: "system-design" },
	{ tagName: "Replication", tagCategory: "system-design" },
	{ tagName: "Sharding", tagCategory: "system-design" },
	{ tagName: "Throttling", tagCategory: "system-design" },
	{ tagName: "Rate Limiting", tagCategory: "system-design" },
	{ tagName: "Event-Driven Architecture", tagCategory: "system-design" },
	{ tagName: "Distributed Systems", tagCategory: "system-design" },
	{ tagName: "CAP Theorem", tagCategory: "system-design" },
	{ tagName: "Teamwork", tagCategory: "behavioral" },
	{ tagName: "Communication", tagCategory: "behavioral" },
	{ tagName: "Leadership", tagCategory: "behavioral" },
	{ tagName: "Conflict Resolution", tagCategory: "behavioral" },
	{ tagName: "Problem-Solving", tagCategory: "behavioral" },
	{ tagName: "Adaptability", tagCategory: "behavioral" },
	{ tagName: "Time Management", tagCategory: "behavioral" },
	{ tagName: "Decision Making", tagCategory: "behavioral" },
	{ tagName: "Creativity", tagCategory: "behavioral" },
	{ tagName: "Stress Management", tagCategory: "behavioral" },
	{ tagName: "Empathy", tagCategory: "behavioral" },
	{ tagName: "Collaboration", tagCategory: "behavioral" },
	{ tagName: "Mentoring", tagCategory: "behavioral" },
	{ tagName: "Feedback", tagCategory: "behavioral" },
	{ tagName: "Motivation", tagCategory: "behavioral" },
	{ tagName: "Accountability", tagCategory: "behavioral" },
	{ tagName: "Negotiation", tagCategory: "behavioral" },
	{ tagName: "Patience", tagCategory: "behavioral" },
	{ tagName: "Networking", tagCategory: "behavioral" },
	{ tagName: "Persuasion", tagCategory: "behavioral" },
	{ tagName: "Agile Methodology", tagCategory: "practical-knowledge" },
	{ tagName: "Security Best Practices", tagCategory: "practical-knowledge" },
	{ tagName: "User Experience (UX)", tagCategory: "practical-knowledge" },
	{ tagName: "User Interface (UI)", tagCategory: "practical-knowledge" },
	{ tagName: "Data Visualization", tagCategory: "practical-knowledge" },
	{ tagName: "Compliance Standards", tagCategory: "practical-knowledge" },
	{ tagName: "Industry Regulations", tagCategory: "practical-knowledge" },
	{ tagName: "Version Control", tagCategory: "practical-knowledge" },
	{ tagName: "Deployment Strategies", tagCategory: "practical-knowledge" },
	{ tagName: "Testing Techniques", tagCategory: "practical-knowledge" },
	{ tagName: "Continuous Integration", tagCategory: "practical-knowledge" },
	{ tagName: "Continuous Deployment", tagCategory: "practical-knowledge" },
	{ tagName: "DevOps", tagCategory: "practical-knowledge" },
	{ tagName: "Containerization", tagCategory: "practical-knowledge" },
	{ tagName: "Infrastructure as Code", tagCategory: "practical-knowledge" },
	{ tagName: "Cloud Computing", tagCategory: "practical-knowledge" },
	{ tagName: "Serverless Architecture", tagCategory: "practical-knowledge" },
	{ tagName: "Mobile Development", tagCategory: "practical-knowledge" },
	{ tagName: "Web Development", tagCategory: "practical-knowledge" },
	{ tagName: "APIs", tagCategory: "practical-knowledge" },
	{ tagName: "Machine Learning", tagCategory: "practical-knowledge" },
	{ tagName: "Artificial Intelligence", tagCategory: "practical-knowledge" },
];

function removeDuplicates(arr: Tag[]) {
	return arr.filter((obj, pos, arr) => {
		return arr.map((mapObj) => mapObj.tagName).indexOf(obj.tagName) === pos;
	});
}

export const tags = removeDuplicates(duplicateTags);

export const categoryColors: { [key: string]: string } = {
	"technical-skills": "#1E90FF",
	"problem-solving": "#32CD32",
	"system-design": "#FFA500",
	behavioral: "#9370DB",
	"practical-knowledge": "#008080",
	default: "#9e9e9e",
};
